name: Run Tests

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v5

          - name: Run test script
            run: ./tests/test_build.sh
